services: 
  pmm-server:
    container_name: pmm-server
    image: percona/pmm-server:2
    volumes:
      - pmm-data:/srv 
    ports:
      - 443:443
    environment:
      - PMM_SERVER=https://admin:admin@ip:443
    networks:
      - mysql

volumes:
  pmm-data:

networks:
  mysql:
 